version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: astro-backend-llm
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${SERVER_HOST}:${SERVER_PORT}/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
